name: Test Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mozmeao/checkout@v1
      - name: Docker build
        run: docker build -t perf-dashboard .
      - name: Test
        run: docker run --rm perf-dashboard npm test
